SET QUOTED_IDENTIFIER ON;
-- CONTACTOS
INSERT INTO PROYECTOSIAV2.dbo.TG_Contacto
SELECT 
'PS-'+CONVERT(VARCHAR,OH.ID), 
PROYECTOSIAV2.dbo.InitCap(OH.FirstName), 
PROYECTOSIAV2.dbo.InitCap(OH.LastName), 
LOWER(OH.Email),
0
FROM (
	SELECT U.ID , U.FirstName, U.LastName, U.Email
FROM TeamMateR12.dbo.TM_User U 
LEFT JOIN TeamMateR12.dbo.TM_Auditor A ON U.ID = A.UserID
WHERE A.UserID IS NULL
  and U.ActiveStatusLID = 0 AND U.ID <> 1
) OH LEFT JOIN PROYECTOSIAV2.dbo.TG_Contacto C ON C.ID = 'PS-'+CONVERT(VARCHAR,OH.ID)
WHERE C.ID IS NULL AND OH.ID IS NOT NULL

-- AUDITORES

INSERT INTO PROYECTOSIAV2.dbo.TG_Contacto
SELECT 
'PS-'+CONVERT(VARCHAR,OH.ID), 
PROYECTOSIAV2.dbo.InitCap(OH.FirstName), 
PROYECTOSIAV2.dbo.InitCap(OH.LastName), 
LOWER(OH.Email),
1
FROM (
	SELECT U.ID ,U.FirstName, U.LastName, U.Email
  FROM TeamMateR12.dbo.TM_User U INNER JOIN TeamMateR12.dbo.TM_Auditor A ON U.ID = A.UserID
	INNER JOIN TeamMateR12.dbo.TM_AuthUserLogin UL ON U.ID = UL.UserID
  WHERE U.ActiveStatusLID = 0 AND U.ID <> 1
) OH LEFT JOIN PROYECTOSIAV2.dbo.TG_Contacto C ON C.ID = 'PS-'+CONVERT(VARCHAR,OH.ID)
WHERE C.ID IS NULL AND OH.ID IS NOT NULL
Select 1 as flag